name: Tests workflow

on: pull_request

jobs:
  build:
    name: Run tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-node@v1
        with:
          node-version: '14.16.0'

      - run: npm ci

      - run: npm test -- --silent --colors
        env:
          CI: true
